**[墨菲定律](https://zh.wikipedia.org/wiki/%E6%91%A9%E8%8F%B2%E5%AE%9A%E7%90%86)：凡是可能出错的事就一定会出错**

之前测试和我反馈测试环境的mysql实例扩容失败，我反复操作，尝试重现BUG，代码逻辑也梳理了几遍，没再重现问题，生产环境也没有客户反馈扩容失败，于是让测试帮忙重现一下这个BUG。我也心存侥幸，只要生产环境不出问题就行

最近一个大项目，我们给一个客户搭建了一整套独享Availible Zone，接入我们的云环境（有点像虚拟运营商的概念）。客户POC测试的时候重现了这个问题，仔细分析了一下原因，ceph层已经将磁盘扩容，但系统层面还需要执行一条命令让文件系统扩容，而xfs文件系统扩容命令xfs_growfs执行条件是设备需要处于挂载状态。

由于以往的生产环境创建的RDS实例是SSD的，所以磁盘被attach的时候，只要fstab有挂载信息，磁盘会被自动挂载，但是demo环境和此次客户的环境都是hdd盘，磁盘还没mount就执行了xfs_growfs，直接抛异常，中断了整个过程。

修复BUG的思路是在resize的时候等待2秒，修改后的代码：
```
def resize_fs(self, mount_point):
    """Resize the filesystem on the specified device."""
    self._check_device_exists()
    # Some OS's will mount a file systems after it's attached if
    # an entry is put in the fstab file (like Trove does).
    # Thus it may be necessary to wait for the mount and then unmount
    # the fs again (since the volume was just attached).
    try:
        if self._wait_for_mount(mount_point, timeout=2):
            if CONF.volume_fstype == 'xfs':
                utils.execute("xfs_growfs", self.device_path,
                                run_as_root=True, root_helper="sudo")
                LOG.debug("Unmounting '%s' before resizing." % mount_point)
                self.unmount(mount_point)
                return

            LOG.debug("Unmounting '%s' before resizing." % mount_point)
            self.unmount(mount_point)

        utils.execute("e2fsck", "-f", "-p", self.device_path,
                        run_as_root=True, root_helper="sudo")
        utils.execute("resize2fs", self.device_path,
                        run_as_root=True, root_helper="sudo")
    except exception.ProcessExecutionError:
        msg = _("Error resizing the filesystem with device '%s'.") % (
            self.device_path)
        log_and_raise(msg)
```

研发人员在发现问题的时候不要心存侥幸，你担心发生的事情，往往会发生，如果造成不可逆的破坏时，损失不可估量